version: "3"
# This is the docker compose for Alfresco Benchmark drivers

services:
    alfresco-bm-load-users:
        image: ${REGISTRY}alfresco/alfresco-bm-load-users:${ALFRESCO_BM_LOAD_USERS_TAG}
        environment:
            JAVA_OPTS : "
                -Dmongo.config.host=${MONGO_HOST}:${MONGO_PORT}
                -Dserver.port=9082
                "
        ports:
            - 9082:9082

    alfresco-bm-rest-api:
        image: ${REGISTRY}alfresco/alfresco-bm-rest-api:${ALFRESCO_BM_REST_API_TAG}
        environment:
            JAVA_OPTS : "
                -Dmongo.config.host=${MONGO_HOST}:${MONGO_PORT}
                -Dserver.port=9083
                "
        ports:
            - 9083:9083