version: "3"
# This is the docker compose for Alfresco Benchmark Manager

services:
    alfresco-bm-manager:
        image: ${REGISTRY}alfresco/alfresco-bm-manager:${ALFRESCO_BM_MANAGER_TAG}
        environment:
            JAVA_OPTS : "
                -Dmongo.config.host=mongo
                "
        ports:
            - 9080:9080
        networks:
            - bm_network

    mongo:
        image: mongo:${MONGO_TAG}
        ports:
            - 27017:27017
        networks:
            - bm_network

networks:
    bm_network:
        driver: bridge