version: "3"
# This is the docker compose for Alfresco Benchmark Manager and all drivers

services:
    alfresco-bm-manager:
        image: ${REGISTRY}alfresco/alfresco-bm-manager:${ALFRESCO_BM_MANAGER_TAG}
        environment:
            JAVA_OPTS : "
                -Dmongo.config.host=mongo
                "
        ports:
            - 9080:9080

    alfresco-bm-load-users-1:
        image: ${REGISTRY}alfresco/alfresco-bm-load-users:${ALFRESCO_BM_LOAD_USERS_TAG}
        environment:
            JAVA_OPTS : "
                -Dmongo.config.host=mongo
                -Dserver.port=9082
                "
        ports:
            - 9082:9082

    alfresco-bm-load-users-2:
        image: ${REGISTRY}alfresco/alfresco-bm-load-users:${ALFRESCO_BM_LOAD_USERS_TAG}
        environment:
            JAVA_OPTS : "
                -Dmongo.config.host=mongo
                -Dserver.port=9083
                "
        ports:
            - 9083:9083

    # alfresco-bm-responsivness:
    #     image: ${REGISTRY}alfresco/alfresco-bm-responsivness:${ALFRESCO_BM_RESPONSIVNESS_TAG}
    #     environment:
    #         JAVA_OPTS : "
    #             -Dmongo.config.host=mongo
    #             -Dserver.port=9084
    #             "
    #     ports:
    #         - 9084:9084

    mongo:
        image: mongo:${MONGO_TAG}
        ports:
            - 27017:27017