#! /bin/sh

### BEGIN INIT INFO
# Provides: Xvfb
# Required-Start: $local_fs $remote_fs
# Required-Stop:
# X-Start-Before:
# Default-Start: 2 3 4 5
# Default-Stop:
### END INIT INFO

N=/etc/init.d/bmserver

set -e

#wget=`GET http://169.254.169.254/latest/user-data`
wget="wget --ftp-user @@FTPUSER@@ --ftp-password @@FTPPWD@@ ftp://@@FTPSERVER@@/software/*"

start()  {
echo -n "Turn off firewall"
   service iptables stop
echo -n "Downloading and starting BM Server"
   rm -rf /opt/bmserver
   mkdir /opt/bmserver
   cd /opt/bmserver
   eval $wget
   chmod +x *.sh
   ./alfresco-benchmark-server.sh
RETVAL=$?
echo
return $RETVAL
}

stop()   {
echo -n "Stopping BM Server"
echo
killall java
echo
return 0
}

case "$1" in
start)
    start
;;
stop)
    stop
;;
restart)
    stop
    start
;;
*)  
    echo "Usage: $N {start|stop|restart}" >&2exit 1
;;
esac

exit 0
