@startuml


cloud "Service Layer"{
    [TestService]
    [LogService]
    [EventService]
    [SessionService]
    [ResultService]
    [TestRunService]
}

[EventController]

[Test]

[TestRunPingTask]

[TestRun]

[EventWork]

[EventProcessor]

[EventProducerRegistry]
[EventProcessorRegistry]

[TestDefaults]

cloud "Mongo DAO Layer"{
    [MongoTestDAO]
}

cloud "Mongo Config DB Layer"{
    [Config MongoDBFactory]
}

cloud "Mongo Test Data DB Layer"{
    [Test Data MongoDBFactory]
}

database "Config Mongo DB" {
    [Config Collections]
}

database "BM Test Data Mongo DB" {
    [Test Data Collections]
}


[TestService] --> [MongoTestDAO]

[Config MongoDBFactory] --> [Config Collections]
[Test Data MongoDBFactory] --> [Test Data Collections]

[LogService] --> [Config MongoDBFactory]
[MongoTestDAO] --> [Config MongoDBFactory]

[EventService] --> [Test Data MongoDBFactory]
[SessionService] --> [Test Data MongoDBFactory]
[ResultService] --> [Test Data MongoDBFactory]


[Test] --> [LogService]
[Test] --> [MongoTestDAO]
[Test] --> [TestRunPingTask]
[Test] --> [TestDefaults]

[TestRunPingTask] ..> [TestRun]
[TestRunPingTask] --> [MongoTestDAO]

[TestRun] --> [MongoTestDAO]
[TestRun] --> [LogService]
[TestRun] ..> [EventController]

[EventController] --> [EventProcessorRegistry]
[EventController] --> [EventProducerRegistry]
[EventController] --> [EventService]
[EventController] --> [ResultService]
[EventController] --> [SessionService]
[EventController] ..> [EventWork]

[EventWork] --> [EventProcessor]
[EventWork] --> [EventProducerRegistry]
[EventWork] --> [EventService]
[EventWork] --> [ResultService]
[EventWork] --> [SessionService]

[TestRunService] --> [MongoTestDAO]
[EventProcessor] ..> [Test Data MongoDBFactory]
@enduml